[2025-05-01T06:52:57.226+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T06:52:57.236+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_build manual__2025-05-01T06:52:56.529884+00:00 [queued]>
[2025-05-01T06:52:57.239+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_build manual__2025-05-01T06:52:56.529884+00:00 [queued]>
[2025-05-01T06:52:57.239+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-01T06:52:57.244+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_build> on 2025-05-01 06:52:56.529884+00:00
[2025-05-01T06:52:57.252+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_build', 'manual__2025-05-01T06:52:56.529884+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/elt_with_dbt.py', '--cfg-path', '/tmp/tmpjo8zgcmw']
[2025-05-01T06:52:57.257+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask dbt_build
[2025-05-01T06:52:57.255+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=405) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T06:52:57.257+0000] {standard_task_runner.py:72} INFO - Started process 406 to run task
[2025-05-01T06:52:57.319+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_build manual__2025-05-01T06:52:56.529884+00:00 [running]> on host 049272b42e61
[2025-05-01T06:52:57.369+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_build' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T06:52:56.529884+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T06:52:56.529884+00:00'
[2025-05-01T06:52:57.369+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-01T06:52:57.383+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-01T06:52:57.385+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt build ---profiles-dir /opt/***/dbt --project-dir /opt/***/project_dbt']
[2025-05-01T06:52:57.389+0000] {subprocess.py:86} INFO - Output:
[2025-05-01T06:52:58.469+0000] {subprocess.py:93} INFO - Usage: dbt build [OPTIONS]
[2025-05-01T06:52:58.470+0000] {subprocess.py:93} INFO - Try 'dbt build -h' for help.
[2025-05-01T06:52:58.470+0000] {subprocess.py:93} INFO - 
[2025-05-01T06:52:58.470+0000] {subprocess.py:93} INFO - Error: No such option: ---profiles-dir (Possible options: --profile, --profiles-dir, --project-dir)
[2025-05-01T06:52:58.551+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-01T06:52:58.556+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-01T06:52:58.558+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_build, run_id=manual__2025-05-01T06:52:56.529884+00:00, execution_date=20250501T065256, start_date=20250501T065257, end_date=20250501T065258
[2025-05-01T06:52:58.562+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-01T06:52:58.563+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 103 for task dbt_build (Bash command failed. The command returned a non-zero exit code 2.; 406)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-01T06:52:58.599+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-01T06:52:58.607+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T06:52:58.608+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
